name: expandable_cardview
description: The ExpandableCard widget provides a customizable card with expandable sections, facilitating the display of detailed information in collapsible sections. 
version: 1.0.8
repository: https://github.com/myaasiinh/expandable_cardview
issue_tracker: https://github.com/myaasiinh/expandable_cardview/issues
maintainer: myaasiinh (@myaasiinh)

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




 